Repository mono/mono, pull requests merged in 2018-02, with the labels that each got.

#6931 [System]: WebConnection.Connect() needs to probe all IP addresses.
  mcs/class/System/System.Net/WebConnection.cs
Labels: area-BCL: System, regression

#7128 [interp] Use frame_addr as base pointer in more places
  mono/mini/interp/interp.c
  mono/mini/mini-exceptions.c
  mono/tests/Makefile.am
Labels: epic: Interpreter

#6892 [metadata] Use getters for MonoClass fields in class.c
  mono/metadata/class-accessors.c
  mono/metadata/class-init.c
  mono/metadata/class-init.h
  mono/metadata/class.c
  mono/metadata/metadata.h
Labels: epic: MonoClass
