Repository mono/mono, pull requests merged in 2018-05, with the labels that each got.

#8753 [System]: Cleanup `SslStream` callbacks and internal validation code.
  mcs/class/Mono.Security/Mono.Security.Interface/CertificateValidationHelper.cs
  mcs/class/System/Mono.Net.Security/CallbackHelpers.cs
  mcs/class/System/Mono.Net.Security/ChainValidationHelper.cs
  mcs/class/System/Mono.Net.Security/LegacySslStream.cs
  mcs/class/System/Mono.Net.Security/MobileAuthenticatedStream.cs
  mcs/class/System/Mono.Net.Security/MobileTlsContext.cs
  mcs/class/System/Mono.Net.Security/NoReflectionHelper.cs
  mcs/class/System/System.Net.Security/SslStream.cs
Labels: area-BCL: System, epic: Client Certificates

#8428 [jit] Decompose CEE_BOX later, to enable more optimization opportunities. Optimize Enum.HasFlags ().
  mono/mini/decompose.c
  mono/mini/intrinsics.c
  mono/mini/method-to-ir.c
  mono/mini/mini-ops.h
  mono/mini/mini.h
  mono/mini/objects.cs
Labels: area-Runtime: JIT

#6456 [debugger] Add locking around tls->frames usage/freeing
  mono/mini/debugger-agent.c
Labels: do-not-merge

#8879 Fix Windows build
  mcs/class/corlib/darwin_net_4_x_corlib.dll.sources
  mcs/class/corlib/linux_net_4_x_corlib.dll.sources
  mcs/class/corlib/net_4_x_corlib.dll.sources
  mcs/class/corlib/win32_net_4_x_corlib.dll.sources
Labels: do-not-merge

#8824 Sanitize TLS handling in the profiler.
  mono/profiler/log.c
  mono/utils/mono-threads.c
  mono/utils/mono-threads.h
Labels: area-Profiler
