Repository mono/mono, pull requests merged in 2019-04, with the labels that each got.

#13801 [llvm] Give LLVM noalias info about alloc functions
  mono/mini/mini-llvm-cpp.cpp
  mono/mini/mini-llvm-cpp.h
  mono/mini/mini-llvm.c
Labels: epic: LLVM CodeGen Quality

#13882 [2019-02] [merp] Fix image size reported
  mcs/tools/upload-to-sentry/UploadToSentry.cs
  mono/mini/mini-exceptions.c
  mono/utils/mono-state.h
Labels: area-Runtime: Crash Reporting

#13884 [2018-10] [merp] Fix image size reported
  mono/mini/mini-exceptions.c
  mono/utils/mono-state.h
Labels: area-Runtime: Crash Reporting

#13886 [2018-08] [merp] Fix image size reported
  mono/mini/mini-exceptions.c
  mono/utils/mono-state.h
Labels: area-Runtime: Crash Reporting

#13892 [image] Create MonoImageStorage to own the image raw data
  mono/metadata/assembly.c
  mono/metadata/coree.c
  mono/metadata/debug-mono-ppdb.c
  mono/metadata/icall-windows.c
  mono/metadata/image.c
  mono/metadata/loader.c
  mono/metadata/metadata-internals.h
  mono/metadata/metadata-verify.c
  mono/metadata/reflection.c
  mono/metadata/w32process.c
  mono/mini/debugger-agent.c
  tools/pedump/pedump.c
Labels: do-not-merge

#13865 [merp] Restore non-assertion behavior in debugger-engine.c
  mono/mini/debugger-engine.c
Labels: area-Debugger, area-Runtime: Crash Reporting

#13623 [Coop] Convert performance counters and performance counter categories.
  configure.ac
  mcs/class/System/System.Diagnostics/PerformanceCounter.cs
  mcs/class/System/System.Diagnostics/PerformanceCounterCategory.cs
  mono/metadata/handle.h
  mono/metadata/icall-def.h
  mono/metadata/icall-table.h
  mono/metadata/mono-perfcounters.c
  mono/metadata/mono-perfcounters.h
  mono/metadata/object-internals.h
  mono/metadata/object.c
Labels: do-not-merge
