Repository mono/mono, pull requests merged in 2019-05, with the labels that each got.

#14354 Fixes #14353
  sdks/wasm/sdk/Mono.WebAssembly.Build/WasmLinkAssemblies.cs
Labels: target-wasm

#14540 [crash] Handle OOM/blocked allocation during crash dumper
  mono/mini/mini-posix.c
Labels: area-Runtime: Crash Reporting

#14539 [crash] Don't waitpid() if fork() fails
  mono/mini/mini-posix.c
Labels: area-Runtime: Crash Reporting

#14279 Infrastructure support / fixes for making compiler server the default
  configure.ac
  mcs/build/common/basic-profile-check.cs
  mcs/build/rules.make
  mcs/build/start-compiler-server.sh
  msvc/scripts/genproj.cs
Labels: do-not-merge
