Repository mono/mono, pull requests merged in 2019-06, with the labels that each got.

#14704 [crash] Move /proc/self/maps crash collection to created JSON blob
  mono/eglib/eglib-remap.h
  mono/eglib/glib.h
  mono/mini/mini-posix.c
  mono/utils/mono-linked-list-set.h
  mono/utils/mono-merp.c
  mono/utils/mono-state.c
Labels: area-Runtime: Crash Reporting

#14734 [wasm] Switch to the LLVM wasm backend.
  mono/mini/aot-compiler.c
  mono/mini/aot-runtime.c
  mono/mini/interp/interp.c
  mono/mini/mini-wasm.h
  mono/utils/mono-threads-wasm.c
  sdks/builds/emscripten-pr-8457.diff
  sdks/builds/wasm.mk
  sdks/wasm/Makefile
  sdks/wasm/packager.cs
Labels: do-not-merge

#14986 [crash] Print native module name when crash privacy disabled
  mono/mini/mini-exceptions.c
Labels: area-Runtime: Crash Reporting

#14621 [wasm] fix most cases of numeric debugger display for wasm
  mono/mini/mini-wasm-debugger.c
  sdks/wasm/library_mono.js
Labels: target-wasm
