Repository mono/mono, pull requests merged in 2019-02, with the labels that each got.

#12687 "Ice Blue": Adding some "Connection Info" properties to SslStream.
  mcs/class/System/Mono.Net.Security/MobileAuthenticatedStream.cs
Labels: area-BCL: Mono.Security

#12864 [crash] Use safer invalid-free test
  mono/tests/libtest.c
Labels: area-Runtime: Crash Reporting

#12946 [crash] Add more detailed reporting for exceptions
  mcs/class/corlib/Test/System/ExceptionTest.cs
  mcs/tools/upload-to-sentry/UploadToSentry.cs
  mono/metadata/object-internals.h
  mono/metadata/threads-types.h
  mono/mini/mini-exceptions.c
  mono/utils/mono-state.c
  mono/utils/mono-state.h
Labels: area-Runtime: Crash Reporting

#13012 [2018-08] Add more detailed reporting for exceptions
  mcs/class/corlib/Test/System/ExceptionTest.cs
  mono/metadata/object-internals.h
  mono/metadata/threads-types.h
  mono/mini/mini-exceptions.c
  mono/utils/mono-state.c
  mono/utils/mono-state.h
Labels: area-Runtime: Crash Reporting

#13013 [2018-10] Add more detailed reporting for exceptions
  mcs/class/corlib/Test/System/ExceptionTest.cs
  mono/metadata/object-internals.h
  mono/metadata/threads-types.h
  mono/mini/mini-exceptions.c
  mono/utils/mono-state.c
  mono/utils/mono-state.h
Labels: area-Runtime: Crash Reporting

#13021 [crash] Move dump_memory_around_ip after the native crash
  mono/mini/mini-posix.c
Labels: area-Runtime: Crash Reporting

#13154 [runtime] Default Interface method fixes.
  mono/metadata/class-init.c
  mono/metadata/loader.c
  mono/mini/interp/transform.c
  mono/mini/method-to-ir.c
  mono/tests/Makefile.am
  mono/tests/dim-constrained3.il
  mono/tests/dim-constrained3_gm.il
  mono/tests/dim-constrainedcall.il
Labels: do-not-merge
